# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73c6e7da10226ae3ad035d8b9f019c017f10730ac52135fdba719370ad6d5aace13a15f2c8402cdcf6981150c8b0488279adf5cf6cff3d903ef18eeda211c684

test:
  secret_key_base: 5fbad23d586eb04a62d36162ab2c89e32669cdfdf365fe7a6cba8838db1f22da805007e7b9a9bfb125e4cd5618de38102236d655ba79af261f1ac7bfbe624d7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
